# -*- coding: utf-8 -*-
"""evaluate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1foDiaHaDpuGU410jcEm5wtVfoW5Si69B
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import os

DATA_DIR = "/content/data/food11/test"
MODEL_PATH = "/content/models/food11_mobilenet.h5"

img_size = (224, 224)

model = tf.keras.models.load_model(MODEL_PATH)

test_gen = ImageDataGenerator(rescale=1./255)

test_data = test_gen.flow_from_directory(
    DATA_DIR,
    target_size=img_size,
    batch_size=32,
    class_mode="categorical",
    shuffle=False
)

loss, acc = model.evaluate(test_data)

print("Test Accuracy:", acc)
print("Test Loss:", loss)