# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1foDiaHaDpuGU410jcEm5wtVfoW5Si69B
"""

import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import os

MODEL_PATH = "/content/models/food11_mobilenet.h5"
CLASS_NAMES = [
    "apple_pie","cheesecake","chicken_curry","french_fries","fried_rice",
    "hamburger","hot_dog","ice_cream","omelette","pizza","sushi"
]

model = tf.keras.models.load_model(MODEL_PATH)

def predict_image(image_path):
    img = load_img(image_path, target_size=(224, 224))
    arr = img_to_array(img) / 255.0
    arr = np.expand_dims(arr, axis=0)

    pred = model.predict(arr)
    idx = np.argmax(pred[0])

    print("Predicted:", CLASS_NAMES[idx])

predict_image("/content/data/food11/test/pizza/103708.jpg")